// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvUMApiyzLxbZxTum2oL0981NJ29xgr-4',
    appId: '1:884639254211:web:56d41827760f5c594e8476',
    messagingSenderId: '884639254211',
    projectId: 'ranck-game-libras',
    authDomain: 'ranck-game-libras.firebaseapp.com',
    storageBucket: 'ranck-game-libras.appspot.com',
    measurementId: 'G-LT3N0GR2LN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj2emssM3bamm0HumwYrszlSxT4ovU7v0',
    appId: '1:884639254211:android:2c05b54e6fb37c404e8476',
    messagingSenderId: '884639254211',
    projectId: 'ranck-game-libras',
    storageBucket: 'ranck-game-libras.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKLRtwZYoucvbL7JmZ2p5aA9yTp5mB3FU',
    appId: '1:884639254211:ios:71445905b855b3474e8476',
    messagingSenderId: '884639254211',
    projectId: 'ranck-game-libras',
    storageBucket: 'ranck-game-libras.appspot.com',
    iosBundleId: 'com.example.ranckGameLibras',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKLRtwZYoucvbL7JmZ2p5aA9yTp5mB3FU',
    appId: '1:884639254211:ios:a6258ac82994b9834e8476',
    messagingSenderId: '884639254211',
    projectId: 'ranck-game-libras',
    storageBucket: 'ranck-game-libras.appspot.com',
    iosBundleId: 'com.example.ranckGameLibras.RunnerTests',
  );
}
